### ISSUE TITLE
Can't preview it.

### ISSUE THREAD

**Issue by jianfzhu** [YU-MITC/moodle-local_yukaltura#2]
I have upload the video success in My Media. but can't play it when i click Preview. also no display in course page. for kaltura server. i can find the upload media and play it. 
here is error message in Moodle.

Not Found
The requested URL /html5/html5lib/v1.8.2/mwEmbedLoader.php/p/102/uiconf_id/6709411 was not found on this server.

Apache/2.2.15 (CentOS) Server at 192.168.70.131 Port 80

**Comment by YU-MITC** [comment]
Hello, jianfzhu.

Does HTTP request arrive at your Kaltura CE server?
Please see log-files in your Kaltura CE server, 
/opt/kaltura/log/kaltura_apache_access.log, kaltura_apache_access_ssl.log, kaltura_apache_errors.log, and kaltura_apache_errors_ssl.log.

If the HTTP request does not arrive at your Kaltura CE server, please see requested URL by using a developer tool on your web browser.
URL, file path and communication protocol (http or https) are correct?

As a supplement, the Kaltura and the Moodle should work on different servers.
And, in order to use our plugins, you should use https protocol at all communication routes.
From the Kaltura to the Moodle, from the Kaltura to web browser, and from the Moodle to web browser.

**Comment by YU-MITC** [comment]
Hello, jianfzhu.

From the error you reported, we seem that you should use other Kaltura player.
Your use a default player (uiconf is 6709411).
It is a flash player, but, our plugins do not support flash players.
Please create a HTML5 player by using the "Universal Studio" in your Kaltura server.
And, please choose the HTML5 player for "My media" and "Media Resource" in setting page of local plugin.

Regards
